config/routes.rb
Rails.application.routes.draw do
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  passwords: 'users/passwords'
}

# guest_login
devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
end

devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

#管理者サイド
get 'admin/homes/top' => 'admin/homes#top', as: 'admin_top'

namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
	resources :tags, only: [:index, :create, :edit, :update]
	resources :notices
  resources :posts, only: [:show, :update]
end


#利用者サイド
root 'user/homes#top'
get 'user/homes/notices/:id' => 'user/homes#notice',as: 'notice'
get 'users/:id/password' => 'user/users#password',as: 'password'
get 'users/favorite' => 'user/users#favorite',as: 'favorite'
get 'users/good_place' => 'user/users#good',as: 'good_place'
get 'users/japan_map' => 'user/posts#japan_map',as: 'japan_map'
get 'users/user_map' => 'user/users#user_map',as: 'user_map'

scope module: :user do
	resources :posts, only: [:index, :show, :new, :create, :destroy] do
	 resource :favorites, only: [:create, :destroy]
   resource :good_places, only: [:create, :destroy]
   resource :alerts,only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
   collection do
    match 'search' => 'posts#search',via: [:get, :post]
   end
	end
  resources :schedules, only: [:index, :create, :destroy]
  resources :users, only: [:show, :edit, :update]
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :good_places, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :alerts, dependent: :destroy
  has_many :schedules, dependent: :destroy
  attachment :image

  validates :name,length: {minimum: 2, maximum: 20}

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "geust"
      user.country = "JP"
      user.password = "123456"
    end
  end

  def active_for_authentication?
    super && self.user_status?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_admin!

	def index
		@users = User.page(params[:page]).per(10)
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to admin_user_path(@user.id)
			flash[:notice] = "ユーザ情報を更新しました"
		else
			flash.now[:alert] = "ユーザ情報の更新ができませんでした"
			render :edit
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :country, :email, :user_status)
	end
end

app/controllers/user/alerts_controller.rb
class User::AlertsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		alert = current_user.alerts.new(post_id: @post.id)
		alert.save
		redirect_to request.referer
		flash[:notice] = "管理者に報告しました"
	end

	def destroy
		@post = Post.find(params[:post_id])
		alert = current_user.alerts.find_by(post_id: @post.id)
		alert.destroy
		redirect_to request.referer
		flash[:notice] = "管理者への報告を取り下げました"
	end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		comment = current_user.comments.new(comment_params)
		comment.post_id = @post.id
		comment.save
	end

	def destroy
		@post = Post.find(params[:post_id])
		comment = Comment.find_by(id: params[:id],post_id: params[:post_id])
		comment.destroy
	end

	private
	def comment_params
		params.require(:comment).permit(:user_id,:post_id,:comment)
	end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		favorite = current_user.favorites.new(post_id: @post.id)
		favorite.save
	end

	def destroy
		@post = Post.find(params[:post_id])
		favorite = current_user.favorites.find_by(post_id: @post.id)
		favorite.destroy
	end
end

app/controllers/user/good_places_controller.rb
class User::GoodPlacesController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		good_place = current_user.good_places.new(post_id: @post.id)
		good_place.save
	end

	def destroy
		@post = Post.find(params[:post_id])
		good_place = current_user.good_places.find_by(post_id: @post.id)
		good_place.destroy
	end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
	def top
		@notices = Notice.where(status: true).limit(10).reverse_order
		@posts = Post.all
		@ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(4).pluck(:post_id))
	end

	def notice
		@notice = Notice.find(params[:id])
	end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
	before_action :authenticate_user!
	def index
		# 公開設定がtrueのみ表示
		if params[:tag_id]
			@tag = Tag.find(params[:tag_id])
			@posts = @tag.posts
			# @posts = @search.result(distinct: true).where(tag_id: params[:tag_id])
		else
			@search_products = @search.result(distinct: true).where(post_status: true).order('id desc').page(params[:page]).per(16)
		end
		@tags = Tag.where(tag_status: true)
		@post_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(4).pluck(:post_id))
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments
		@comment = Comment.new
	end

	def new
		@post = Post.new
		@post.post_images.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to post_path(@post.id)
			flash[:notice] = "投稿できました"
		else
			flash.now[:alert] = "投稿できませんでした"
			render :new
		end
	end

	def destroy
		# @post = Post.find(params[:id])
		@post = current_user.posts.find(params[:id])
		if @post.destroy
			redirect_to posts_path
			flash[:notice] = "削除ができました"
		else
			flash.now[:alert] = "削除ができませんでした"
			render :show
		end
	end




	private
	def post_params
		params.require(:post).permit(:title,:country,:prefecture,:city,:location,:body,post_images_images:[],tag_ids:[])
	end

	def search_params
		params.require(:q).permit(:sorts)
	end

end

app/controllers/user/schedules_controller.rb
class User::SchedulesController < ApplicationController
	before_action :authenticate_user!

	require "date"

	def index
		@schedule = Schedule.new
		@schedules = Schedule.where(user_id: current_user)
		@today = Date.current
	end

	def create
		@schedule = Schedule.new(schedule_params)
		@schedule.user_id = current_user.id
		@schedules = Schedule.where(user_id: current_user)
		if @schedule.save
			redirect_to schedules_path
			flash[:notice] = "スケジュールを計画しました"
		else
			render :index
			flash[:alert] = "スケジュールの投稿に失敗しました"
		end

	end

	def destroy
		@schedule = Schedule.find(params[:id])
		if @schedule.destroy
			redirect_to request.referer
			flash[:notice] = "スケジュールを削除しました"
		else
			flash.now[:alert] = "スケジュールの削除に失敗しました"
			render :index
		end
	end

	private
	def schedule_params
		params.require(:schedule).permit(:content, :start_day, :end_day)
	end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit]

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.page(params[:page]).per(10)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
        # パスワードを変更するとログアウトしてしまうので、再ログインが必要
       		sign_in(@user, bypass: true)
       		flash[:notice] = "ユーザ情報を更新しました"
       	 	redirect_to user_path(@user.id)
      	else
			render :edit
			flash.now[:alert] = "ユーザ情報を更新できませんでした"
      	end
	end

	def password
		@user = User.find(params[:id])
	end

	def good
		@good_places =GoodPlace.where(user_id: current_user.id)
	end

	def favorite
		@favorites = Favorite.where(user_id: current_user.id)
	end

	private
	def user_params
		params.require(:user).permit(:name,:email,:country,:image,:password)
	end

	def correct_user
     user = User.find(params[:id])
      if user != current_user
        redirect_to user_path(current_user)
   	 end
  	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :check_guest, only: :create

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]



  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def new_guest
    user = User.guest
    sign_in user
    redirect_to posts_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/alerts_helper.rb
module User::AlertsHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/views/user/users/edit.html.erb
<div class="container">
<h2>ユーザ情報編集</h2>


<%= form_for(@user,url:user_path(@user)) do |f| %>
	<div class="row">
		<div class="col-md-6">
			<%= attachment_image_tag(@user,:image,size:"200x200", class: "user_image", fallback: "no_image.jpg") %>
			<%= f.attachment_field :image,id:"user_image_preview" %>
		</div>
		<div class="col-md-6">
			<div class="field">
				<%= f.label "名前" %>
				<%= f.text_field :name,class: "form-control" %>
				<% if @user.errors.include?(:name) %>
	    			<span style="color: red;"><%= @user.errors.full_messages_for(:name).first %></span>
				<% end %>
			</div>
			<div class="field">
				<%= f.label "出身" %>
				<%= f.country_select :country,{ priority_countries:["JP"]}, autofocus: true, format: :with_alpha2, autocomplete: "country",class: "form-control" %>
				<% if @user.errors.include?(:country) %>
	    			<span style="color: red;"><%= @user.errors.full_messages_for(:country).first %></span>
				<% end %>
			</div>
			<div class="field">
				<%= f.label "メールアドレス" %>
				<%= f.email_field :email,class: "form-control" %>
				<% if @user.errors.include?(:email) %>
	    			<span style="color: red;"><%= @user.errors.full_messages_for(:email).first %></span>
				<% end %>
			</div>
			<%= f.submit "編集する",class: "form-control" %>
		</div>
	</div>
<% end %>

<%= link_to "詳細に戻る",user_path(@user) %>
</div>

app/views/user/users/favorite.html.erb
<div class="container">
<h2>いいね一覧</h2>

	<div class="row">
		<% @favorites.each do |favorite| %>
			<% post = Post.find(favorite.post_id) %>
			<div class="mr-0 ml-0 post-box">
				<div class="post-content">
					<%= link_to post_path(post) do %>
						<div class="content-top">
							<div class="slick_index">
								<% post.post_images.each do |image| %>
									<div class="slick_index_image">
										<%= attachment_image_tag(image,:image ,:fill ,200,200) %>
									</div>
								<% end %>
							</div>
						</div>
						<div class="content-bottom">
							<div class="post-title">
								<%= post.title %>
							</div>
							<div class="post_place">
								<span></span>
								<% if post.prefecture.present? %>
									<i class="fas fa-map-marker-alt" style="color: green;"></i><%= post.prefecture %>
								<% else %>
									<i class="fas fa-map-marker-alt" style="color: green;"></i><%= post.city %>
								<% end %>
								<div class="post-favorite">
									<i class="fas fa-heart" style="color: red;"></i>
									<%= post.favorites.count %>
									<i class="fas fa-globe-asia" style="color: dodgerblue;"></i>
									<%= post.good_places.count %>
									<i class="fas fa-comments" style="color: lightslategray;"></i>
									<%= post.comments.count %>
								</div>
								<div class="post-time">
									<%= post.created_at.strftime("%Y-%m-%d") %>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/user/users/good.html.erb
<div class="container">
<h2>行きたい場所</h2>

	<div class="row">
		<% @good_places.each do |good_place| %>
			<% post = Post.find(good_place.post_id) %>
			<div class="mr-0 ml-0 post-box">
				<div class="post-content">
					<%= link_to post_path(post) do %>
						<div class="content-top">
							<div class="slick_index">
								<% post.post_images.each do |image| %>
									<div class="slick_index_image">
										<%= attachment_image_tag(image,:image ,:fill ,200,200) %>
									</div>
								<% end %>
							</div>
						</div>
						<div class="content-bottom">
							<div class="post-title">
								<%= post.title %>
							</div>
							<div class="post_place">
								<span></span>
								<% if post.prefecture.present? %>
									<i class="fas fa-map-marker-alt" style="color: green;"></i><%= post.prefecture %>
								<% else %>
									<i class="fas fa-map-marker-alt" style="color: green;"></i><%= post.city %>
								<% end %>
								<div class="post-favorite">
									<i class="fas fa-heart" style="color: red;"></i>
									<%= post.favorites.count %>
									<i class="fas fa-globe-asia" style="color: dodgerblue;"></i>
									<%= post.good_places.count %>
									<i class="fas fa-comments" style="color: lightslategray;"></i>
									<%= post.comments.count %>
								</div>
								<div class="post-time">
									<%= post.created_at.strftime("%Y-%m-%d") %>
								</div>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/user/users/password.html.erb
<div class="container">
	<h2>パスワード変更</h2>

	<%= form_for(@user,url:user_path(@user)) do |f| %>
	<div class="col-md-6">
		<div class="field">
			<%= f.label 'パスワード変更' %>
			<%= f.password_field :password, autocomplete: "password",class: "form-control" %>
		</div>
		<div class="field">
		    <%= f.label 'パスワード変更確認' %>
		    <%= f.password_field :password_confirmation, autocomplete: "password",class: "form-control" %>
		</div>
		<div class="submit">
	    	<%= f.submit "変更する",class: "btn" %>
	    </div>
	</div>
	<% end %>
</div>

app/views/user/users/show.html.erb
<div class="container user_show">
<div class="page-sub-title">マイページ</div>

<div class="page-sub-title">ユーザ情報</div>

<div class="row user-detail-box">
	<div class="col-md-3">
		<!-- ユーザ情報 -->
		<%= attachment_image_tag(@user,:image,size:"150x150", class: "user_image", fallback: "no_image.jpg") %>
	</div>
	<div class="col-md-8">
		<div class="row user-detail">
			<div class="col-md-6">
				<p>ユーザ名:<%= @user.name %></p>
			</div>
			<% if @user == current_user %>
				<div class="col-md-6">
					<%= link_to "ユーザ情報編集", edit_user_path(@user.id),class: "btn btn-primary user-detail-button" %>
				</div>
				<div class="col-md-6">
					<%= link_to "パスワード変更", password_path(@user.id),class: "btn btn-primary user-detail-button" %>
				</div>
				<div class="col-md-6">
					<%= link_to "旅行の設定", schedules_path,class: "btn btn-primary user-detail-button" %>
				</div>
				<div class="col-md-6">
					<%= link_to "行きたい一覧",good_place_path,class: "btn btn-primary user-detail-button" %>
				</div>
				<div class="col-md-6">
					<%= link_to "いいね一覧",favorite_path,class: "btn btn-primary user-detail-button" %>
				</div>
			<% else %>
			<% end %>
		</div>
	</div>
</div>

<div class="page-sub-title">投稿一覧</div>
	<%= render '/user/posts/post_index', {posts: @posts} %>
</div>