config/routes.rb
Rails.application.routes.draw do
devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations',
  passwords: 'users/passwords'
}

# guest_login
devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admins/sessions#new_guest'
end

devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
end

#管理者サイド
get 'admin/homes/top' => 'admin/homes#top', as: 'admin_top'

namespace :admin do
  resources :users, only: [:index, :show, :edit, :update]
	resources :tags, only: [:index, :create, :edit, :update]
	resources :notices
  resources :posts, only: [:show, :update]
end


#利用者サイド
root 'user/homes#top'
get 'user/homes/notices/:id' => 'user/homes#notice',as: 'notice'
get 'users/:id/password' => 'user/users#password',as: 'password'
get 'users/favorite' => 'user/users#favorite',as: 'favorite'
get 'users/good_place' => 'user/users#good',as: 'good_place'
get 'users/japan_map' => 'user/posts#japan_map',as: 'japan_map'
get 'users/user_map' => 'user/users#user_map',as: 'user_map'

scope module: :user do
	resources :posts, only: [:index, :show, :new, :create, :destroy] do
	 resource :favorites, only: [:create, :destroy]
   resource :good_places, only: [:create, :destroy]
   resource :alerts,only: [:create, :destroy]
   resources :comments, only: [:create, :destroy]
   collection do
    match 'search' => 'posts#search',via: [:get, :post]
   end
	end
  resources :schedules, only: [:index, :create, :destroy]
  resources :users, only: [:show, :edit, :update]
end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'admin@example.com') do |admin|
      admin.password = SecureRandom.urlsafe_base64
    end
  end

  def active_for_authentication?
    super
  end
end

app/models/alert.rb
class Alert < ApplicationRecord
	belongs_to :user
	belongs_to :post

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates :comment, presence: true,length: { maximum: 20 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/good_place.rb
class GoodPlace < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/notice.rb
class Notice < ApplicationRecord
	attachment :image

	validates :title, presence: true,length: { maximum: 15 }
	validates :body, presence: true,length: { maximum: 150 }
	validates :image, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :post_images, dependent: :destroy
	accepts_attachments_for :post_images, attachment: :image
	has_many :favorites, dependent: :destroy
	has_many :good_places, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :alerts, dependent: :destroy
	has_many :post_tags,dependent: :destroy
	has_many :tags, through: :post_tags,dependent: :destroy

	validates :title, presence: true,length: { maximum: 15 }
	validates :body, presence: true,length: { maximum: 150 }
	validates :post_images, presence: true,length: { maximum: 10 }
	validates :country, presence: true
	validates :location, presence: true,length: { maximum: 15 }

	enum prefecture: {
    北海道:'北海道',青森県:'青森県',岩手県:'岩手県',宮城県:'宮城県',秋田県:'秋田県',山形県:'山形県',福島県:'福島県',
    茨城県:'茨城県',栃木県:'栃木県',群馬県:'群馬県',埼玉県:'埼玉県',千葉県:'千葉県',東京都:'東京都',神奈川県:'神奈川県',
    新潟県:'新潟県',富山県:'富山県',石川県:'石川県',福井県:'福井県',山梨県:'山梨県',長野県:'長野県',
    岐阜県:'岐阜県',静岡県:'静岡県',愛知県:'愛知県',三重県:'三重県',
    滋賀県:'滋賀県',京都府:'京都府',大阪府:'大阪府',兵庫県:'兵庫県',奈良県:'奈良県',和歌山県:'和歌山県',
    鳥取県:'鳥取県',島根県:'島根県',岡山県:'岡山県',広島県:'広島県',山口県:'山口県',
    徳島県:'徳島県',香川県:'香川県',愛媛県:'愛媛県',高知県:'高知県',
    福岡県:'福岡県',佐賀県:'佐賀県',長崎県:'長崎県',熊本県:'熊本県',大分県:'大分県',宮崎県:'宮崎県',鹿児島県:'鹿児島県',沖縄県:'沖縄県'
  	}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def good_placed_by?(user)
		good_places.where(user_id: user.id).exists?
	end

	def alerted_by?(user)
		alerts.where(user_id: user.id).exists?
	end

	ransacker :favorites_count do
    	query = '(SELECT COUNT(favorites.post_id) FROM favorites where favorites.post_id = posts.id GROUP BY favorites.post_id)'
    	Arel.sql(query)
  	end

  	ransacker :good_places_count do
    	query = '(SELECT COUNT(good_places.post_id) FROM good_places where good_places.post_id = posts.id GROUP BY good_places.post_id)'
    	Arel.sql(query)
  	end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :post
	attachment :image
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
	belongs_to :post
	belongs_to :tag
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	belongs_to :user

	validates :content, presence: true,length: { maximum: 15 }
	validates :start_day, presence: true
	validates :end_day, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :post_tags,dependent: :destroy
	has_many :posts, through: :post_tags,dependent: :destroy

	validates :tag_name, presence: true,length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :good_places, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :alerts, dependent: :destroy
  has_many :schedules, dependent: :destroy
  attachment :image

  validates :name,length: {minimum: 2, maximum: 20}

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "geust"
      user.country = "JP"
      user.password = "123456"
    end
  end

  def active_for_authentication?
    super && self.user_status?
  end
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController
	before_action :authenticate_admin!
	def index
		@notices = Notice.page(params[:page]).per(10).reverse_order
	end

	def show
		@notice = Notice.find(params[:id])
	end

	def new
		@notice = Notice.new
	end

	def create
		@notice = Notice.new(notice_params)
		if @notice.save
			redirect_to admin_notice_path(@notice.id)
			flash[:notice] = "お知らせを作成しました"
		else
			flash.now[:alert] = "お知らせの作成に失敗しました"
			render :new
		end
	end

	def edit
		@notice = Notice.find(params[:id])
	end

	def update
		@notice = Notice.find(params[:id])
		if @notice.update(notice_params)
			redirect_to admin_notice_path(@notice.id)
			flash[:notice] = "お知らせ情報を更新しました"
		else
			flash.now[:alert] = "お知らせの更新に失敗しました"
			render :edit
		end
	end

	def destroy
		@notice = Notice.find(params[:id])
		if @notice.destroy
			redirect_to admin_notices_path
			flash[:notice] = "お知らせを削除しました"
		else
			flash.now[:alert] = "お知らせの削除に失敗しました"
			render :show
		end
	end

	private
	def notice_params
		params.require(:notice).permit(:title,:body,:image,:status,:notice_tag)
	end
end

app/controllers/application_controller.rb
	class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	before_action :set_search

	def after_sign_in_path_for(resource)
		case resource
		when Admin
			admin_top_path
		when User
			posts_path
		end
	end

	def after_sign_up_path_for(resource)
		case resource
		when Admin
			admin_top_path
		when User
			posts_path
		end
	end

	def after_sign_out_path_for(resource)
		if resource == :admins
			new_admin_session_path
		else
			root_path
		end
	end

	def set_search
		@search = Post.ransack(params[:q])
	end

	private
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :country])
	end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/notices_helper.rb
module Admin::NoticesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/notices/_notice_create.html.erb
<div class="row">
	<div class="col-md-4">
		<%= attachment_image_tag(notice,:image,size:"200x200", fallback: "no_image.jpg") %>
		<%= f.attachment_field :image,id: "notice_image_preview" %>
		<% if notice.errors.include?(:image) %>
    		<span style="color: red;"><%= notice.errors.full_messages_for(:image).first %></span>
		<% end %>
	</div>
	<div class="col-md-8">
		<%= f.label :title, "タイトル",class: "m-0" %>
		<%= f.text_field :title,placeholder: "タイトルを入力して下さい",class: "form-control" %>
		<% if notice.errors.include?(:title) %>
    		<span style="color: red;"><%= notice.errors.full_messages_for(:title).first %></span>
		<% end %>
		<%= f.label :body, "内容",class: "m-0" %>
		<%= f.text_area :body,placeholder: "内容を入力して下さい",class: "form-control" %>
		<% if notice.errors.include?(:body) %>
    		<span style="color: red;"><%= notice.errors.full_messages_for(:body).first %></span>
		<% end %>
		<div class="notice_tag_setting">
			<span>タグ設定</span>
			<%= f.radio_button :notice_tag,true, checked: true %>
			<%= f.label :notice_tag, "重要なお知らせ",value: true %>
			<%= f.radio_button :notice_tag,false %>
			<%= f.label :notice_tag, "アップデート情報",value: false %>
		</div>
		<div class="notice_status">
			<%= f.label :status, "公開設定" %>
			<%= f.radio_button :status,true,checked: true %>
			<%= f.label :status,"公開",value: true %>
			<%= f.radio_button :status,false %>
			<%= f.label :status,"非公開",value: false %>
		</div>
		<div class="submit">
			<%= f.submit "投稿",class: "btn btn-primary" %>
		</div>
	</div>
</div>

app/views/admin/notices/_notice_index.html.erb
<table class="table table-hover border">
	<thead>
		<tr>
			<th></th>
			<th>タイトル</th>
			<th>アップデート日</th>
			<% if admin_signed_in? %>
			<th>公開状況</th>
			<th></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% notices.each do |notice| %>
		<tr>
			<td>
				<% if notice.notice_tag == true %>
					<label class="notice_tag_true">重要な情報</label>
				<% else %>
					<label class="notice_tag_false">アップデート情報</label>
				<% end %>
			</td>
			<td><%= link_to notice.title,notice_path(notice) %></td>
			<td><%= notice.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
			<% if admin_signed_in? %>
			<td>
				<% if notice.status == true %>
					<label>公開中</label>
				<% else %>
					<label>非公開</label>
				<% end %>
			</td>
			<td><%= link_to "詳細へ", admin_notice_path(notice) %></td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/admin/notices/edit.html.erb
<div class="container">
<div class="page-sub-title">編集</div>

<%= form_for(@notice,url: admin_notice_path) do |f| %>
	<%= render 'notice_create',{notice: @notice, f: f} %>
<% end %>
</div>

app/views/admin/notices/index.html.erb
<div class="container">
<div class="page-sub-title">一覧画面</div>

<div data-turbolinks="false">
	<%= link_to "+",new_admin_notice_path,class: "btn btn-primary rounded-circle float-right" %>
</div>

<%= render 'notice_index', {notices: @notices} %>

<%= paginate @notices %>
</div>

app/views/admin/notices/new.html.erb
<div class="container">
<div class="page-sub-title">新規作成</div>

<%= form_for(@notice,url: admin_notices_path) do |f| %>
	<%= render 'notice_create',{notice: @notice, f: f} %>
<% end %>
</div>

app/views/admin/notices/show.html.erb
<div class="container">
<div class="page-sub-title">詳細画面</div>

<div class="row">
	<div class="col-md-4">
		<%= attachment_image_tag(@notice,:image,:fill,200,200) %>
	</div>
	<div class="col-md-8">
		<h3>タイトル</h3>
		<%= @notice.title %>
		<h3>内容</h3>
		<%= @notice.body %>
		<h3>詳細</h3>
		<div class="notice_tag">
			<span>タグ</span>
			<% if @notice.notice_tag == true %>
				<label class="notice_tag_true">重要な情報</label>
			<% else %>
				<label class="notice_tag_false">アップデート情報</label>
			<% end %>
		</div>
		<div class="notice_status">
			<span>公開情報</span>
			<% if @notice.status == true %>
				<label class="notice_status_true">公開中</label>
			<% else %>
				<label class="notice_status_false">非公開</label>
			<% end %>
		</div>
		<div class="notice-create">
			<span>作成日</span>
			<%= @notice.created_at.strftime("%Y-%m-%d %H:%M") %>
		</div>
		<div class="notice-update">
			<span>最終修正日</span>
			<%= @notice.updated_at.strftime("%Y-%m-%d %H:%M") %>
		</div>
	</div>
</div>

<%= link_to "一覧画面", admin_notices_path,class: "btn btn-primary" %>
<%= link_to "編集画面", edit_admin_notice_path,class: "btn btn-primary" %>
</div>